---
clear-day: â˜€ï¸
clear-night: â­
rain: ğŸŒ§
snow: ğŸŒ¨
sleet: ğŸŒ¨
wind: ğŸŒ¬
fog: ğŸŒ«
cloudy: â˜ï¸
partly-cloudy-day: â›…
partly-cloudy-night: â›…
hail: âš ï¸
thunderstorm: ğŸŒ©
tornado: âš ï¸
default: âš ï¸
moon:
    - ğŸŒ‘
    - ğŸŒ’
    - ğŸŒ“
    - ğŸŒ”
    - ğŸŒ•
    - ğŸŒ–
    - ğŸŒ—
    - ğŸŒ˜
